project_name: ???
experiment_name: ???
step: ???

merger:
  operation: merge
  backend: fsdp
  local_dir: checkpoints/${project_name}/${experiment_name}/global_step_${step}/actor
  hf_model_config_path: checkpoints/${project_name}/${experiment_name}/global_step_${step}/actor/huggingface
  target_dir: checkpoints/${project_name}/${experiment_name}/global_step_${step}/actor/huggingface
