experiment_name: ???
step: ???
seed: ???
model_dir: checkpoints/e3_math/${experiment_name}/global_step_${step}/actor/huggingface
output_dir: data/e3_math/${experiment_name}/global_step_${step}

dataset:
  path: parquet
  data_dir: data/e3_math
  data_files: test.parquet
  split: train

llm:
  model: ${model_dir}
  tensor_parallel_size: 1
  dtype: bfloat16
  seed: ${seed}
  gpu_memory_utilization: 0.9
  enforce_eager: False

sampling_params:
  temperature: 1.0
  top_p: 1.0
  top_k: -1
  max_tokens: 32768
