model_name: ???
seed: ???
output_dir: data/e3_math/${model_name}

dataset:
  path: parquet
  data_dir: data/e3_math
  data_files: test.parquet
  split: train

llm:
  model: ${mode_name}
  tensor_parallel_size: 1
  dtype: bfloat16
  seed: ${seed}
  gpu_memory_utilization: 0.9
  enforce_eager: False

sampling_params:
  temperature: 0.6
  top_p: 0.95
  top_k: 20
  max_tokens: 32768
