experiment_name: ???
step: ???
model_dir: checkpoints/e3_math/${experiment_name}/global_step_${step}/actor

merger_config:
  operation: merge
  backend: fsdp
  target_dir: ${model_dir}/huggingface
  local_dir: ${model_dir}
  hf_model_config_path: ${model_dir}/huggingface
